### PR TITLE
Make the HDU number public.

### PR DESCRIPTION
**Pull request by cjordan**
Hi again, just a tweak this time.  This will help some error messages I'm developing in my own code.  Let me know if there should be more added with this change.

### CODE REVIEW

**Comment by mindriot101** [comment]
Thanks for this suggestion. I'd be tempted to either rename the variable (`number`) if we're going to expose it. Otherwise I'm happy with this change. Would you be able to make that change?

**Comment by cjordan** [comment]
Done (did a force push to keep the change in a single keep commit) - compiles fine and tests pass for me.

Thanks!

**Comment by mindriot101** [comment]
Looks great, thanks! I'll merge when the checks are done.

**Comment by mindriot101** [comment]
Thanks for this!

**Pull request merged**
