### PR TITLE
Eta077 main

### PR DESCRIPTION
**Pull request by mindriot101**
Based on #159, we update the `Dockerfile` to support local development for non-unix platforms.

### CODE REVIEW

**Comment by eta077** [comment]
I'm able to successfully build a container from the updated Dockerfile, but when running the `./bin/test -t all` command, I get the following error:

```
error: failed to run custom build command for `cast v0.2.7`

Caused by:
  process didn't exit successfully: `/project/target/debug/build/cast-dd26f4947cc4de68/build-script-build` (exit status: 1)
  --- stderr
  /project/target/debug/build/cast-dd26f4947cc4de68/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /project/target/debug/build/cast-dd26f4947cc4de68/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: build failed
test failed with exit code 101
```

**Comment by mindriot101** [comment]
@eta077 can you try running with something like:

```
docker run --rm -it -v $(pwd):/project -e CARGO_TARGET_DIR=/tmp <image> ./bin/test -t all
```

and let me know if that works? I'm wondering if it is trying to use existing files in your `target` dir

**Comment by eta077** [comment]
@mindriot101 looks like that was the issue, the test command works after running `cargo clean` - thanks so much for your help!

**Comment by mindriot101** [comment]
That's great, it sounds like some files from your `target` folder were being used to link against new compiled outputs. I think either a `cargo clean` first, or setting the `CARGO_TARGET_DIR` as I showed is enough to ensure a clean build. I'll merge this into the `main` branch. Thank you for helping test the crate!

**Pull request merged**
